### ISSUE TITLE
KeyError occur when select ernie_3.0_base_zh to convert

### ISSUE THREAD

**Issue by AbuNLP** [heiheiyoyo/uie_pytorch#16]
run:
python convert.py -i ernie-3.0-base-zh --no_validate_output

got:

2023-03-01 01:34:35.798449: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[2023-03-01 01:34:37,186] [    INFO] - Downloading resource files...
[2023-03-01 01:34:37,187] [    INFO] - Downloading ernie_3.0_base_zh.pdparams from https://bj.bcebos.com/paddlenlp/models/transformers/ernie_3.0/ernie_3.0_base_zh.pdparams
[2023-03-01 01:37:55,405] [    INFO] - Downloading ernie_3.0_base_zh_vocab.txt from https://bj.bcebos.com/paddlenlp/models/transformers/ernie_3.0/ernie_3.0_base_zh_vocab.txt
[2023-03-01 01:37:55,798] [    INFO] - ====================save config file====================                                                     
[2023-03-01 01:37:55,800] [    INFO] - ====================save vocab file====================
[2023-03-01 01:37:55,801] [    INFO] - ====================extract weights====================
Traceback (most recent call last):
  File "convert.py", line 468, in <module>
    do_main()
  File "convert.py", line 427, in do_main
    extract_and_convert(args.input_model, args.output_model, verbose=True)
  File "convert.py", line 297, in extract_and_convert
    del paddle_paddle_params['StructuredToParameterName@@']
**KeyError: 'StructuredToParameterName@@'**

**Comment by Elegant-Spider** [comment]
遇到了同样的问题
