### ISSUE TITLE
本地执行finetune.py 模型微调提示@runtime_checkable异常

### ISSUE THREAD

**Issue by 15874920993** [heiheiyoyo/uie_pytorch#44]
"D:\Program Files\anaconda3\envs\uie\python.exe" "D:/Program Files/JetBrains/PyCharm 2022.2.2/plugins/python/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 49998 --file D:\work\develop\python_work\uie_work\uie_pytorch\finetune.py --train_path ./data/train.txt --dev_path ./data/dev.txt --save_dir ./checkpoint --learning_rate 1e-5 --batch_size 4 --max_seq_len 512 --num_epochs 100 --model uie_base_pytorch --seed 1000 --logging_steps 10 --valid_steps 100 --device cpu 
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2022.2.2\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2022.2.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\work\develop\python_work\uie_work\uie_pytorch\finetune.py", line 253, in <module>
    do_train()
  File "D:\work\develop\python_work\uie_work\uie_pytorch\finetune.py", line 44, in do_train
    train_data_loader = DataLoader(
  File "D:\Program Files\anaconda3\envs\uie\lib\site-packages\torch\utils\data\dataloader.py", line 200, in __init__
    if isinstance(dataset, IterableDataset):
  File "D:\Program Files\anaconda3\envs\uie\lib\typing.py", line 1498, in __instancecheck__
    raise TypeError("Instance and class checks can only be used with"
TypeError: Instance and class checks can only be used with @runtime_checkable protocols

**Comment by 15874920993** [comment]
有哪位大佬遇到过吗？
